package Interface;

import Utilitaires.Base;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Benjamin
 */
public class ProjetBDD extends javax.swing.JFrame {

    //Variables
    private boolean estCo;
    private ArrayList<String> _listeTable;
    private ArrayList<String[]> _listeCrit1, _listeCrit2;
    private Base maBase;
    private String _typeCritJoin1, _typeCritJoin2, _typeCritJoin3;
    private ArrayList<ArrayList<String>> resultatJointure;
    
    
    public ProjetBDD() {
        initComponents();
        estCo = true;
        maBase = new Base("bb111272", "bb111272", "ufrsciencestech.u-bourgogne.fr", 25561, "ensb2013", this); //Depuis l'extérieur
        initVar();
    }
    
    public void initVar()
    {
        _listeTable = new ArrayList<>();
        _listeCrit1 = new ArrayList<>();
        _listeCrit2 = new ArrayList<>();
        resultatJointure = new ArrayList<>();
        jPanel1.setVisible(false);
        jButtonGraphe.setVisible(false);
        jButtonJointure.setVisible(false);
        jButtonJointure2.setVisible(false);
        jButtonResultat.setVisible(false);
        jPanelCritJoin1.setVisible(false);
        jPanelCritJoin2.setVisible(false);
        jPanel6.setVisible(false);
        _typeCritJoin1 = "";
        _typeCritJoin2 = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonConnDeco = new javax.swing.JButton();
        jCheckBoxDistanceServeur = new javax.swing.JCheckBox();
        jCheckBoxStockDB = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxTable1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTable2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelCritJoin2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCritJoin2 = new javax.swing.JComboBox();
        jPanelCritJoin1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCritJoin1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputConsole = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonJointure = new javax.swing.JButton();
        jComboBoxCritJoin3 = new javax.swing.JComboBox();
        jTextCritere3 = new javax.swing.JTextField();
        jButtonJointure2 = new javax.swing.JButton();
        jButtonGraphe = new javax.swing.JButton();
        jButtonResultat = new javax.swing.JButton();
        jButtonGrapheV2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projet BDD");
        setMinimumSize(new java.awt.Dimension(400, 75));
        setPreferredSize(new java.awt.Dimension(424, 800));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix de la Connexion"));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        jButtonConnDeco.setText("Connexion");
        jButtonConnDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnDecoActionPerformed(evt);
            }
        });

        jCheckBoxDistanceServeur.setText("Local");
        jCheckBoxDistanceServeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDistanceServeurActionPerformed(evt);
            }
        });

        jCheckBoxStockDB.setText("Stockage du Graphe sur la DB");
        jCheckBoxStockDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStockDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonConnDeco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jCheckBoxStockDB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxDistanceServeur)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnDeco)
                    .addComponent(jCheckBoxStockDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDistanceServeur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix des Tables"));

        jPanel1.setMaximumSize(new java.awt.Dimension(370, 200));

        jComboBoxTable1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        jComboBoxTable1.setEnabled(false);
        jComboBoxTable1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTable1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Première table");

        jComboBoxTable2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        jComboBoxTable2.setEnabled(false);
        jComboBoxTable2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTable2ItemStateChanged(evt);
            }
        });

        jLabel2.setText("Deuxième table");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix des Critères de Jointure"));

        jLabel6.setText("Critère de Jointure");

        jComboBoxCritJoin2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        jComboBoxCritJoin2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCritJoin2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelCritJoin2Layout = new javax.swing.GroupLayout(jPanelCritJoin2);
        jPanelCritJoin2.setLayout(jPanelCritJoin2Layout);
        jPanelCritJoin2Layout.setHorizontalGroup(
            jPanelCritJoin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCritJoin2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCritJoin2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxCritJoin2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCritJoin2Layout.setVerticalGroup(
            jPanelCritJoin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCritJoin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCritJoin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Critère de Jointure");

        jComboBoxCritJoin1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        jComboBoxCritJoin1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCritJoin1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelCritJoin1Layout = new javax.swing.GroupLayout(jPanelCritJoin1);
        jPanelCritJoin1.setLayout(jPanelCritJoin1Layout);
        jPanelCritJoin1Layout.setHorizontalGroup(
            jPanelCritJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCritJoin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCritJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxCritJoin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCritJoin1Layout.setVerticalGroup(
            jPanelCritJoin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCritJoin1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCritJoin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanelCritJoin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCritJoin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCritJoin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCritJoin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        OutputConsole.setEditable(false);
        OutputConsole.setColumns(20);
        OutputConsole.setLineWrap(true);
        OutputConsole.setRows(5);
        OutputConsole.setWrapStyleWord(true);
        OutputConsole.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        OutputConsole.setMaximumSize(new java.awt.Dimension(250, 500000));
        OutputConsole.setMinimumSize(new java.awt.Dimension(250, 250));
        OutputConsole.setPreferredSize(new java.awt.Dimension(250, 250));
        jScrollPane1.setViewportView(OutputConsole);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Jointure"));

        jLabel4.setText("Ou");

        jLabel3.setText("Valeur : ");

        jButtonJointure.setText("Jointure");
        jButtonJointure.setMaximumSize(new java.awt.Dimension(100, 33));
        jButtonJointure.setMinimumSize(new java.awt.Dimension(100, 33));
        jButtonJointure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJointureActionPerformed(evt);
            }
        });

        jComboBoxCritJoin3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        jComboBoxCritJoin3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCritJoin3ItemStateChanged(evt);
            }
        });

        jButtonJointure2.setText("Jointure V2");
        jButtonJointure2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJointure2ActionPerformed(evt);
            }
        });

        jButtonGraphe.setText("Graphe");
        jButtonGraphe.setMaximumSize(new java.awt.Dimension(100, 33));
        jButtonGraphe.setMinimumSize(new java.awt.Dimension(100, 33));
        jButtonGraphe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrapheActionPerformed(evt);
            }
        });

        jButtonResultat.setText("Affichage Resultat");
        jButtonResultat.setMaximumSize(new java.awt.Dimension(100, 33));
        jButtonResultat.setMinimumSize(new java.awt.Dimension(100, 33));
        jButtonResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultatActionPerformed(evt);
            }
        });

        jButtonGrapheV2.setText("Graphe V2");
        jButtonGrapheV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrapheV2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonResultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButtonJointure, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(70, 70, 70))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGraphe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonJointure2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jComboBoxCritJoin3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCritere3)
                    .addComponent(jButtonGrapheV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGraphe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGrapheV2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCritJoin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCritere3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonJointure2)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonJointure, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnDecoActionPerformed
        if(estCo)
        {
            initVar();
            estCo = false;
            jButtonConnDeco.setText("Déconnexion");
            deroulement();
        }
        else
        {
            estCo = true;
            jButtonConnDeco.setText("Connexion");
            jPanel1.setVisible(false);
            jPanelCritJoin1.setVisible(false);
            jPanelCritJoin2.setVisible(false);
            try {
                maBase.seDeconnecter();
            } catch (SQLException ex) {
                Logger.getLogger(ProjetBDD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonConnDecoActionPerformed

    private void jComboBoxTable2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTable2ItemStateChanged
        if (jComboBoxTable2.getSelectedIndex() > 0)
        {
            jPanelCritJoin2.setVisible(true);
            majComboBoxCritJoin(2,evt.getItem().toString());
            majComboBoxCritJoin3();
        }
        else
            jPanelCritJoin2.setVisible(false);
    }//GEN-LAST:event_jComboBoxTable2ItemStateChanged

    private void jComboBoxTable1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTable1ItemStateChanged
        if (jComboBoxTable1.getSelectedIndex() > 0)
        {
            jPanelCritJoin1.setVisible(true);
            majComboBoxCritJoin(1,evt.getItem().toString());
            majComboBoxCritJoin3();
        }
        else
            jPanelCritJoin1.setVisible(false);
    }//GEN-LAST:event_jComboBoxTable1ItemStateChanged

    private void jComboBoxCritJoin2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCritJoin2ItemStateChanged
        if (jComboBoxCritJoin2.getSelectedIndex() > 0)
        {
            _typeCritJoin2 = _listeCrit2.get(jComboBoxCritJoin2.getSelectedIndex() - 1)[1];
            if(evt.getStateChange() == ItemEvent.SELECTED)
            {
                if(jComboBoxCritJoin1.getSelectedIndex() > 0)
                {
                    jButtonGraphe.setVisible(true);
                    jButtonJointure.setVisible(true);
                    jButtonResultat.setVisible(false);
                    jPanel6.setVisible(true);
                }
            }
            else
            {
                jButtonGraphe.setVisible(false);
                jButtonJointure.setVisible(false);
                jButtonResultat.setVisible(false);
                jPanel6.setVisible(false);
            }
        }
        else
        {
            jButtonGraphe.setVisible(false);
            jButtonJointure.setVisible(false);
            jButtonResultat.setVisible(false);
            jPanel6.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxCritJoin2ItemStateChanged

    private void jComboBoxCritJoin1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCritJoin1ItemStateChanged
        if (jComboBoxCritJoin1.getSelectedIndex() > 0)
        {
            _typeCritJoin1 = _listeCrit1.get(jComboBoxCritJoin1.getSelectedIndex() - 1)[1];
            if(evt.getStateChange() == ItemEvent.SELECTED)
            {
                if(jComboBoxCritJoin2.getSelectedIndex() > 0)
                {
                    jButtonGraphe.setVisible(true);
                    jButtonJointure.setVisible(true);
                    jButtonResultat.setVisible(false);
                    jPanel6.setVisible(true);
                }
            }
            else
            {
                jButtonGraphe.setVisible(false);
                jButtonJointure.setVisible(false);
                jButtonResultat.setVisible(false);
                jPanel6.setVisible(false);
            }
        }
        else
        {
            jButtonGraphe.setVisible(false);
            jButtonJointure.setVisible(false);
            jButtonResultat.setVisible(false);
            jPanel6.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxCritJoin1ItemStateChanged

    private void jButtonGrapheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrapheActionPerformed
        maBase.choixCreateGraphe(jComboBoxTable1.getSelectedItem().toString(),
                                jComboBoxCritJoin1.getSelectedItem().toString(),
                                jComboBoxTable2.getSelectedItem().toString(),
                                jComboBoxCritJoin2.getSelectedItem().toString(),
                                jCheckBoxStockDB.isSelected(),
                                true,
                                jComboBoxCritJoin3.getSelectedItem().toString(),
                                jTextCritere3.getText());
    }//GEN-LAST:event_jButtonGrapheActionPerformed

    private void jCheckBoxDistanceServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDistanceServeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDistanceServeurActionPerformed

    private void jButtonJointureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJointureActionPerformed
        lancementJointure(1);
    }//GEN-LAST:event_jButtonJointureActionPerformed

    private void jButtonResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultatActionPerformed
        AffichageResultatForm arf = new AffichageResultatForm(this,resultatJointure);
        arf.setVisible(true);
    }//GEN-LAST:event_jButtonResultatActionPerformed

    private void jCheckBoxStockDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStockDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxStockDBActionPerformed

    private void jComboBoxCritJoin3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCritJoin3ItemStateChanged
        if (jComboBoxCritJoin3.getSelectedIndex() > 0 & evt.getStateChange() == ItemEvent.SELECTED)
        {
            _typeCritJoin3 = jComboBoxCritJoin3.getSelectedItem().toString();
            jButtonJointure2.setVisible(true);
        }
        else
            jButtonJointure2.setVisible(false);
    }//GEN-LAST:event_jComboBoxCritJoin3ItemStateChanged

    private void jButtonJointure2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJointure2ActionPerformed
                                                       
        lancementJointure(2);
    }//GEN-LAST:event_jButtonJointure2ActionPerformed

    private void jButtonGrapheV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrapheV2ActionPerformed
        maBase.choixCreateGraphe(jComboBoxTable1.getSelectedItem().toString(),
                                jComboBoxCritJoin1.getSelectedItem().toString(),
                                jComboBoxTable2.getSelectedItem().toString(),
                                jComboBoxCritJoin2.getSelectedItem().toString(),
                                jCheckBoxStockDB.isSelected(),
                                false,
                                jComboBoxCritJoin3.getSelectedItem().toString(),
                                jTextCritere3.getText());
    }//GEN-LAST:event_jButtonGrapheV2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ProjetBDD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ProjetBDD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ProjetBDD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ProjetBDD.class.getName()).log(Level.SEVERE, null, ex);
                }
                new ProjetBDD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputConsole;
    private javax.swing.JButton jButtonConnDeco;
    private javax.swing.JButton jButtonGraphe;
    private javax.swing.JButton jButtonGrapheV2;
    private javax.swing.JButton jButtonJointure;
    private javax.swing.JButton jButtonJointure2;
    private javax.swing.JButton jButtonResultat;
    private javax.swing.JCheckBox jCheckBoxDistanceServeur;
    private javax.swing.JCheckBox jCheckBoxStockDB;
    private javax.swing.JComboBox jComboBoxCritJoin1;
    private javax.swing.JComboBox jComboBoxCritJoin2;
    private javax.swing.JComboBox jComboBoxCritJoin3;
    private javax.swing.JComboBox jComboBoxTable1;
    private javax.swing.JComboBox jComboBoxTable2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCritJoin1;
    private javax.swing.JPanel jPanelCritJoin2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCritere3;
    // End of variables declaration//GEN-END:variables

    public void majComboBoxTable()
    {
        jComboBoxTable1.setEnabled(true);
        jComboBoxTable2.setEnabled(true);
        
        jComboBoxTable1.removeAllItems();
        jComboBoxTable2.removeAllItems();
        
        jComboBoxTable1.addItem("...");
        jComboBoxTable2.addItem("...");
        
        for( String table : _listeTable)
        {
            jComboBoxTable1.addItem(table);
            jComboBoxTable2.addItem(table);
        }
        
    }
    
    public void majComboBoxCritJoin(int crit, String table)
    {
        ArrayList<String[]> listeCrit = new ArrayList<>();
        try {
            listeCrit = new ArrayList<>(maBase.selectCrit(table));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Fail", JOptionPane.ERROR_MESSAGE);
        }        
        if(crit == 1)
        {
            _listeCrit1 = new ArrayList<>(listeCrit);            
            jComboBoxCritJoin1.setEnabled(true);        
            jComboBoxCritJoin1.removeAllItems();
            jComboBoxCritJoin1.addItem("...");        
        }
        else
        {
            _listeCrit2 = new ArrayList<>(listeCrit); 
            jComboBoxCritJoin2.setEnabled(true);
            jComboBoxCritJoin2.removeAllItems();
            jComboBoxCritJoin2.addItem("...");
        }
        
        for( String[] attribut : listeCrit)
        {
            if(crit == 1)
                jComboBoxCritJoin1.addItem(attribut[0]);
            else
                jComboBoxCritJoin2.addItem(attribut[0]);
        }
        
    }
    
    public void majComboBoxCritJoin3()
    {           
        jComboBoxCritJoin3.setEnabled(true);        
        jComboBoxCritJoin3.removeAllItems();
        jComboBoxCritJoin3.addItem("...");        
        
        
        for( String[] attribut : _listeCrit1)
        {
            if( _listeCrit1.indexOf(attribut) != (jComboBoxCritJoin1.getSelectedIndex()))
                jComboBoxCritJoin3.addItem(attribut[0]);
        }
        
        for( String[] attribut : _listeCrit2)
        {
            if( _listeCrit2.indexOf(attribut) != (jComboBoxCritJoin2.getSelectedIndex()))
                jComboBoxCritJoin3.addItem(attribut[0]);
        }
    }
    
    public void deroulement()
    {
        if(jCheckBoxDistanceServeur.isSelected())
        {
            maBase.setAdresse("butor");
            maBase.setPort(1521);
        }
        else
            maBase.setAdresse("ufrsciencestech.u-bourgogne.fr");
        estCo = false;
        jButtonConnDeco.setText("Déconnexion");
        jPanel1.setVisible(true);
        try {
            maBase.seConnecter();
            _listeTable = new ArrayList<>(maBase.selectTable("user"));
            majComboBoxTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Fail", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void printOuput(String message)
    {
        OutputConsole.setText(message + "\n\n" +OutputConsole.getText());
    }
    
    public void lancementJointure(int choix)
    {
        if(jComboBoxTable1.getSelectedItem().equals(jComboBoxTable2.getSelectedItem())) //C'est les mêmes tables
            JOptionPane.showMessageDialog(null, "Les deux tables sont identiques !", "Erreur : Jointure imposible", JOptionPane.ERROR_MESSAGE);
        else if(! _typeCritJoin1.equals(_typeCritJoin2))
            JOptionPane.showMessageDialog(null, "Les deux colonnes sont de types différents !", "Erreur : Jointure imposible", JOptionPane.ERROR_MESSAGE);
        else{
            if(choix == 1)
                resultatJointure = new ArrayList<>(maBase.jointure(jComboBoxTable1.getSelectedItem().toString(),
                                jComboBoxCritJoin1.getSelectedItem().toString(),
                                jComboBoxTable2.getSelectedItem().toString(),
                                jComboBoxCritJoin2.getSelectedItem().toString(),
                                jCheckBoxStockDB.isSelected(),
                                true,
                                jComboBoxCritJoin3.getSelectedItem().toString(),
                                jTextCritere3.getText()));
            else
                resultatJointure = new ArrayList<>(maBase.jointure(jComboBoxTable1.getSelectedItem().toString(),
                                jComboBoxCritJoin1.getSelectedItem().toString(),
                                jComboBoxTable2.getSelectedItem().toString(),
                                jComboBoxCritJoin2.getSelectedItem().toString(),
                                jCheckBoxStockDB.isSelected(),
                                false,
                                jComboBoxCritJoin3.getSelectedItem().toString(),
                                jTextCritere3.getText()));
            if(resultatJointure.isEmpty())
                JOptionPane.showMessageDialog(null, "VIDE", "Erreur : Jointure imposible", JOptionPane.ERROR_MESSAGE);
            else
                jButtonResultat.setVisible(true);
        
        }
    }
}
